// <auto-generated />
using System;
using APTOS.EOM.ATPService.ATPEFModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APTOS.EOM.ATPService.Migrations
{
    [DbContext(typeof(ATPContext))]
    [Migration("20200222082200_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APTOS.EOM.ATPService.ATPEFModels.AtpItem", b =>
                {
                    b.Property<long>("AtpitemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ATPItemId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AtpTransactionId");

                    b.Property<DateTime>("CreateDatetimeUtc")
                        .HasColumnType("datetime");

                    b.Property<bool?>("Isnonmerchflag")
                        .HasColumnName("isnonmerchflag");

                    b.Property<long>("Iteminternalid")
                        .HasColumnName("iteminternalid");

                    b.Property<int>("LineId");

                    b.Property<string>("LogisticsData")
                        .HasMaxLength(500);

                    b.Property<long?>("Productexternalid")
                        .HasColumnName("productexternalid");

                    b.Property<long?>("Productinternalid")
                        .HasColumnName("productinternalid");

                    b.Property<int?>("QuantityRequested");

                    b.Property<string>("SalesChannelData")
                        .HasMaxLength(500);

                    b.Property<string>("Shippingmethod")
                        .HasColumnName("shippingmethod")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdateDatetimeUtc")
                        .HasColumnType("datetime");

                    b.HasKey("AtpitemId");

                    b.HasIndex("AtpTransactionId");

                    b.ToTable("AtpItem");
                });

            modelBuilder.Entity("APTOS.EOM.ATPService.ATPEFModels.AtpTransaction", b =>
                {
                    b.Property<long>("AtpTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("Cartexternalid")
                        .HasColumnName("cartexternalid");

                    b.Property<DateTime>("CreateDatetimeUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("LogisticsData")
                        .HasColumnType("text");

                    b.Property<int?>("Orderinternalid")
                        .HasColumnName("orderinternalid");

                    b.Property<string>("SalesChannelData")
                        .HasColumnType("text");

                    b.Property<decimal?>("Totaldeliverycost")
                        .HasColumnName("totaldeliverycost")
                        .HasColumnType("numeric(19, 4)");

                    b.Property<DateTime>("UpdateDatetimeUtc")
                        .HasColumnType("datetime");

                    b.HasKey("AtpTransactionId");

                    b.ToTable("AtpTransaction");
                });

            modelBuilder.Entity("APTOS.EOM.ATPService.ATPEFModels.AtpTransactionNotes", b =>
                {
                    b.Property<long>("AtpTransactionNotesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AtpTransactionId");

                    b.Property<string>("AtptransContext")
                        .HasColumnName("atptransContext")
                        .HasMaxLength(50);

                    b.Property<string>("AtptransNote")
                        .HasColumnName("atptransNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDatetimeUtc")
                        .HasColumnType("datetime");

                    b.Property<long?>("NoteReferenceId");

                    b.Property<DateTime>("UpdateDatetimeUtc")
                        .HasColumnType("datetime");

                    b.HasKey("AtpTransactionNotesId");

                    b.HasIndex("AtpTransactionId");

                    b.ToTable("AtpTransactionNotes");
                });

            modelBuilder.Entity("APTOS.EOM.ATPService.ATPEFModels.ItemDelivery", b =>
                {
                    b.Property<long>("ItemDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AtpitemId")
                        .HasColumnName("ATPItemId");

                    b.Property<string>("Carrier")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreateDatetimeUtc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DcDeliveryDatetimeUtc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeliveryDatetimeUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("DeliveryTimeWindow")
                        .HasMaxLength(20);

                    b.Property<int?>("GroupId");

                    b.Property<decimal?>("ItemDeliveryCost")
                        .HasColumnType("decimal(19, 4)");

                    b.Property<int?>("LeadTimeInDays");

                    b.Property<DateTime?>("PickDatetimeUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("ServiceLevel")
                        .HasMaxLength(50);

                    b.Property<int?>("ServiceStatusId");

                    b.Property<DateTime?>("ShippingDatetimeUtc")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("UpdateDatetimeUtc")
                        .HasColumnType("datetime");

                    b.HasKey("ItemDeliveryId");

                    b.HasIndex("AtpitemId");

                    b.HasIndex("ServiceStatusId");

                    b.ToTable("ItemDelivery");
                });

            modelBuilder.Entity("APTOS.EOM.ATPService.ATPEFModels.ItemReservation", b =>
                {
                    b.Property<long>("ItemReservationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AtpitemId")
                        .HasColumnName("ATPItemId");

                    b.Property<DateTime>("CreateDatetimeUtc")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsQuantityReservedFlag");

                    b.Property<string>("PickupLocationExternalId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("PickupLocationInternalId");

                    b.Property<int>("ServiceStatusId");

                    b.Property<string>("ShippingLocationExternalId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ShippingLocationInternalId");

                    b.Property<DateTime>("UpdateDatetimeUtc")
                        .HasColumnType("datetime");

                    b.HasKey("ItemReservationId");

                    b.HasIndex("AtpitemId");

                    b.HasIndex("ServiceStatusId");

                    b.ToTable("ItemReservation");
                });

            modelBuilder.Entity("APTOS.EOM.ATPService.ATPEFModels.ServiceConfiguration", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive");

                    b.Property<string>("SettingComments")
                        .HasMaxLength(500);

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("SettingKey")
                        .HasName("PK_atpinfrastructure");

                    b.ToTable("ServiceConfiguration");
                });

            modelBuilder.Entity("APTOS.EOM.ATPService.ATPEFModels.ServiceStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("StatusId")
                        .HasName("status_pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("status_atpstatusname_key");

                    b.ToTable("ServiceStatus");
                });

            modelBuilder.Entity("APTOS.EOM.ATPService.ATPEFModels.AtpItem", b =>
                {
                    b.HasOne("APTOS.EOM.ATPService.ATPEFModels.AtpTransaction", "AtpTransaction")
                        .WithMany("AtpItem")
                        .HasForeignKey("AtpTransactionId")
                        .HasConstraintName("FK_ATPItem_AtpTransaction");
                });

            modelBuilder.Entity("APTOS.EOM.ATPService.ATPEFModels.AtpTransactionNotes", b =>
                {
                    b.HasOne("APTOS.EOM.ATPService.ATPEFModels.AtpTransaction", "AtpTransaction")
                        .WithMany("AtpTransactionNotes")
                        .HasForeignKey("AtpTransactionId")
                        .HasConstraintName("FK_AtpTransactionNotes_AtpTransaction");
                });

            modelBuilder.Entity("APTOS.EOM.ATPService.ATPEFModels.ItemDelivery", b =>
                {
                    b.HasOne("APTOS.EOM.ATPService.ATPEFModels.AtpItem", "Atpitem")
                        .WithMany("ItemDelivery")
                        .HasForeignKey("AtpitemId")
                        .HasConstraintName("FK_ItemDelivery_ATPItem");

                    b.HasOne("APTOS.EOM.ATPService.ATPEFModels.ServiceStatus", "ServiceStatus")
                        .WithMany("ItemDelivery")
                        .HasForeignKey("ServiceStatusId")
                        .HasConstraintName("FK_ItemDelivery_ATPStatus");
                });

            modelBuilder.Entity("APTOS.EOM.ATPService.ATPEFModels.ItemReservation", b =>
                {
                    b.HasOne("APTOS.EOM.ATPService.ATPEFModels.AtpItem", "Atpitem")
                        .WithMany("ItemReservation")
                        .HasForeignKey("AtpitemId")
                        .HasConstraintName("FK_ItemReservation_ATPItem");

                    b.HasOne("APTOS.EOM.ATPService.ATPEFModels.ServiceStatus", "ServiceStatus")
                        .WithMany("ItemReservation")
                        .HasForeignKey("ServiceStatusId")
                        .HasConstraintName("FK_ItemReservation_ATPStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
